# Generated by Django 5.1.3 on 2024-11-18 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='statement',
            name='status',
            field=models.CharField(choices=[('Новый', 'Новый'), ('В обработке', 'В обработке'), ('Выполнен', 'Выполнен')], default='Новый', max_length=200, verbose_name='Статус'),
        ),
    ]
